//
// ConfigItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ConfigItem: JSONEncodable {
    public var property: String?
    public var defaultValue: String?
    public var description: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["property"] = self.property
        nillableDictionary["defaultValue"] = self.defaultValue
        nillableDictionary["description"] = self.description
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
