//
// ContinuousQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ContinuousQuery: JSONEncodable {
    public var name: String
    public var query: String
    public var options: [String:AnyObject]?
    public var tableName: String?
    public var partitionKeys: [String]?

    public init(name: String, query: String) {
        self.name = name
        self.query = query
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["query"] = self.query
        nillableDictionary["options"] = self.options?.encodeToJSON()
        nillableDictionary["tableName"] = self.tableName
        nillableDictionary["partitionKeys"] = self.partitionKeys?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
