//
// EmailActionConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EmailActionConfig: JSONEncodable {
    public var title: String?
    public var content: String?
    public var columnName: String?
    public var defaultValues: [String:String]?
    public var richText: Bool?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["content"] = self.content
        nillableDictionary["columnName"] = self.columnName
        nillableDictionary["defaultValues"] = self.defaultValues?.encodeToJSON()
        nillableDictionary["richText"] = self.richText
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
