//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Event: JSONEncodable {
    public var collection: String
    public var api: EventContext
    public var properties: AnyObject

    public init(collection: String, api: EventContext, properties: AnyObject) {
        self.collection = collection
        self.api = api
        self.properties = properties
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["collection"] = self.collection
        nillableDictionary["api"] = self.api.encodeToJSON()
        nillableDictionary["properties"] = self.properties
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
