//
// EventContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventContext: JSONEncodable {
    public var apiKey: String
    public var library: Library
    public var apiVersion: String
    public var uploadTime: Int64
    public var checksum: String
    public var plugins: [MappingPlugin]

    public init(apiKey: String, library: Library, apiVersion: String, uploadTime: Int64, checksum: String, plugins: [MappingPlugin]) {
        self.apiKey = apiKey
        self.library = library
        self.apiVersion = apiVersion
        self.uploadTime = uploadTime
        self.checksum = checksum
        self.plugins = plugins
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["api_key"] = self.apiKey
        nillableDictionary["library"] = self.library.encodeToJSON()
        nillableDictionary["api_version"] = self.apiVersion
        nillableDictionary["upload_time"] = self.uploadTime.encodeToJSON()
        nillableDictionary["checksum"] = self.checksum
        nillableDictionary["plugins"] = self.plugins.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
