//
// Execute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Execute: JSONEncodable {
    public enum ExportType: String { 
        case Avro = "AVRO"
        case Csv = "CSV"
        case Json = "JSON"
    }
    /**  */
    public var query: String
    /**  */
    public var exportType: ExportType
    /**  */
    public var limit: Int32?

    public init(query: String, exportType: ExportType) {
        self.query = query
        self.exportType = exportType
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["query"] = self.query
        nillableDictionary["export_type"] = self.exportType.rawValue
        nillableDictionary["limit"] = self.limit?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
