//
// MaterializedView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MaterializedView: JSONEncodable {
    public var tableName: String
    public var name: String
    public var query: String
    public var updateInterval: String?
    public var incremental: Bool?
    public var options: [String:AnyObject]?
    public var lastUpdate: NSDate?

    public init(tableName: String, name: String, query: String) {
        self.tableName = tableName
        self.name = name
        self.query = query
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["table_name"] = self.tableName
        nillableDictionary["name"] = self.name
        nillableDictionary["query"] = self.query
        nillableDictionary["update_interval"] = self.updateInterval
        nillableDictionary["incremental"] = self.incremental
        nillableDictionary["options"] = self.options?.encodeToJSON()
        nillableDictionary["last_update"] = self.lastUpdate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
