//
// Measure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Measure: JSONEncodable {
    public enum Aggregation: String { 
        case Count = "COUNT"
        case CountUnique = "COUNT_UNIQUE"
        case Sum = "SUM"
        case Minimum = "MINIMUM"
        case Maximum = "MAXIMUM"
        case Average = "AVERAGE"
        case ApproximateUnique = "APPROXIMATE_UNIQUE"
    }
    public var column: String
    public var aggregation: Aggregation

    public init(column: String, aggregation: Aggregation) {
        self.column = column
        self.aggregation = aggregation
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["column"] = self.column
        nillableDictionary["aggregation"] = self.aggregation.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
