//
// MetadataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MetadataResponse: JSONEncodable {
    public var columns: [SchemaField]?
    public var identifierColumn: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["columns"] = self.columns?.encodeToJSON()
        nillableDictionary["identifierColumn"] = self.identifierColumn
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
