//
// ModuleDescriptor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ModuleDescriptor: JSONEncodable {
    public var name: String?
    public var description: String?
    public var className: String?
    public var isActive: Bool?
    public var condition: Condition?
    public var properties: [ConfigItem]?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["className"] = self.className
        nillableDictionary["isActive"] = self.isActive
        nillableDictionary["condition"] = self.condition?.encodeToJSON()
        nillableDictionary["properties"] = self.properties?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
