//
// Ordering.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Ordering: JSONEncodable {
    public enum Ordering: String { 
        case Ascending = "ASCENDING"
        case Descending = "DESCENDING"
    }
    public var ordering: Ordering?
    public var index: Int32?
    public var expression: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ordering"] = self.ordering?.rawValue
        nillableDictionary["index"] = self.index?.encodeToJSON()
        nillableDictionary["expression"] = self.expression
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
