//
// ProjectApiKeys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProjectApiKeys: JSONEncodable {
    public var masterKey: String?
    public var readKey: String?
    public var writeKey: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["master_key"] = self.masterKey
        nillableDictionary["read_key"] = self.readKey
        nillableDictionary["write_key"] = self.writeKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
