//
// ProjectAddCustomFieldsToSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProjectAddCustomFieldsToSchema: JSONEncodable {
    public enum SchemaType: String { 
        case Avro = "AVRO"
    }
    public var collection: String?
    public var schemaType: SchemaType?
    public var schema: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["collection"] = self.collection
        nillableDictionary["schema_type"] = self.schemaType?.rawValue
        nillableDictionary["schema"] = self.schema
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
