//
// ProjectCheckApiKeys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProjectCheckApiKeys: JSONEncodable {
    public var keys: [ProjectApiKeys]?
    public var project: String?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["keys"] = self.keys?.encodeToJSON()
        nillableDictionary["project"] = self.project
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
