//
// QueryResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class QueryResult: JSONEncodable {
    public var metadata: [SchemaField]
    /** Each row is an array that contains the values for the columns that are defined in metadata property. */
    public var result: [[AnyObject]]?
    public var error: QueryError
    public var properties: [String:AnyObject]
    public var failed: Bool?

    public init(metadata: [SchemaField], error: QueryError, properties: [String:AnyObject]) {
        self.metadata = metadata
        self.error = error
        self.properties = properties
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["metadata"] = self.metadata.encodeToJSON()
        nillableDictionary["result"] = self.result?.encodeToJSON()
        nillableDictionary["error"] = self.error.encodeToJSON()
        nillableDictionary["properties"] = self.properties.encodeToJSON()
        nillableDictionary["failed"] = self.failed
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
