//
// RealTimeQueryResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RealTimeQueryResult: JSONEncodable {
    public var start: Int64?
    public var end: Int64?
    public var result: AnyObject?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["start"] = self.start?.encodeToJSON()
        nillableDictionary["end"] = self.end?.encodeToJSON()
        nillableDictionary["result"] = self.result
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
