//
// RealtimeQueryTable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RealtimeQueryTable: JSONEncodable {
    public var tableName: String?
    public var filter: String?
    public var measure: Measure?
    public var dimensions: [String]?
    public var aggregate: Bool?
    public var dateStart: NSDate?
    public var dateEnd: NSDate?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["table_name"] = self.tableName
        nillableDictionary["filter"] = self.filter
        nillableDictionary["measure"] = self.measure?.encodeToJSON()
        nillableDictionary["dimensions"] = self.dimensions?.encodeToJSON()
        nillableDictionary["aggregate"] = self.aggregate
        nillableDictionary["date_start"] = self.dateStart?.encodeToJSON()
        nillableDictionary["date_end"] = self.dateEnd?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
