//
// Recipe.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Recipe: JSONEncodable {
    public enum Strategy: String { 
        case Default = "DEFAULT"
        case Specific = "SPECIFIC"
    }
    public var strategy: Strategy?
    public var collections: [String:CollectionDefinition]?
    public var materializedViews: [MaterializedView]?
    public var continuousQueries: [ContinuousQuery]?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["strategy"] = self.strategy?.rawValue
        nillableDictionary["collections"] = self.collections?.encodeToJSON()
        nillableDictionary["materialized_views"] = self.materializedViews?.encodeToJSON()
        nillableDictionary["continuous_queries"] = self.continuousQueries?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
