//
// ResponseQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ResponseQuery: JSONEncodable {
    public var groupBy: [GroupBy]?
    public var orderBy: [Ordering]?
    public var limit: Int64?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["groupBy"] = self.groupBy?.encodeToJSON()
        nillableDictionary["orderBy"] = self.orderBy?.encodeToJSON()
        nillableDictionary["limit"] = self.limit?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
