//
// RetentionQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RetentionQuery: JSONEncodable {
    public enum DateUnit: String { 
        case Day = "DAY"
        case Week = "WEEK"
        case Month = "MONTH"
    }
    public var firstAction: RetentionAction?
    public var returningAction: RetentionAction?
    public var dimension: String?
    public var dateUnit: DateUnit?
    public var period: Int32?
    public var startDate: NSDate?
    public var endDate: NSDate?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["first_action"] = self.firstAction?.encodeToJSON()
        nillableDictionary["returning_action"] = self.returningAction?.encodeToJSON()
        nillableDictionary["dimension"] = self.dimension
        nillableDictionary["date_unit"] = self.dateUnit?.rawValue
        nillableDictionary["period"] = self.period?.encodeToJSON()
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
