//
// SchemaFieldInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SchemaFieldInfo: JSONEncodable {
    public enum ModelType: String { 
        case String = "STRING"
        case Integer = "INTEGER"
        case Decimal = "DECIMAL"
        case Double = "DOUBLE"
        case Long = "LONG"
        case Boolean = "BOOLEAN"
        case Date = "DATE"
        case Time = "TIME"
        case Timestamp = "TIMESTAMP"
        case Binary = "BINARY"
        case ArrayString = "ARRAY_STRING"
        case ArrayInteger = "ARRAY_INTEGER"
        case ArrayDecimal = "ARRAY_DECIMAL"
        case ArrayDouble = "ARRAY_DOUBLE"
        case ArrayLong = "ARRAY_LONG"
        case ArrayBoolean = "ARRAY_BOOLEAN"
        case ArrayDate = "ARRAY_DATE"
        case ArrayTime = "ARRAY_TIME"
        case ArrayTimestamp = "ARRAY_TIMESTAMP"
        case ArrayBinary = "ARRAY_BINARY"
        case MapString = "MAP_STRING"
        case MapInteger = "MAP_INTEGER"
        case MapDecimal = "MAP_DECIMAL"
        case MapDouble = "MAP_DOUBLE"
        case MapLong = "MAP_LONG"
        case MapBoolean = "MAP_BOOLEAN"
        case MapDate = "MAP_DATE"
        case MapTime = "MAP_TIME"
        case MapTimestamp = "MAP_TIMESTAMP"
        case MapBinary = "MAP_BINARY"
    }
    public var category: String?
    public var type: ModelType?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["category"] = self.category
        nillableDictionary["type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
