//
// Sorting.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Sorting: JSONEncodable {
    public enum Order: String { 
        case Asc = "asc"
        case Desc = "desc"
    }
    public var column: String?
    public var order: Order?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["column"] = self.column
        nillableDictionary["order"] = self.order?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
