//
// UserContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserContext: JSONEncodable {
    public var apiKey: String
    public var library: Library
    public var uploadTime: Int64
    public var checksum: String

    public init(apiKey: String, library: Library, uploadTime: Int64, checksum: String) {
        self.apiKey = apiKey
        self.library = library
        self.uploadTime = uploadTime
        self.checksum = checksum
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["api_key"] = self.apiKey
        nillableDictionary["library"] = self.library.encodeToJSON()
        nillableDictionary["upload_time"] = self.uploadTime.encodeToJSON()
        nillableDictionary["checksum"] = self.checksum
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
