//
// UserEmailActionBatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserEmailActionBatch: JSONEncodable {
    public var filter: String?
    public var eventFilters: [EventFilter]?
    public var config: EmailActionConfig?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["filter"] = self.filter
        nillableDictionary["event_filters"] = self.eventFilters?.encodeToJSON()
        nillableDictionary["config"] = self.config?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
