//
// UserIncrementProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserIncrementProperty: JSONEncodable {
    public var api: UserContext?
    public var id: String?
    public var property: String?
    public var value: Double?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["api"] = self.api?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["property"] = self.property
        nillableDictionary["value"] = self.value
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
