//
// UserSearchUsers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserSearchUsers: JSONEncodable {
    public var columns: [String]?
    public var filter: String?
    public var eventFilters: [EventFilter]?
    public var sorting: Sorting?
    public var offset: String?
    public var limit: Int32?

    public init() {
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["columns"] = self.columns?.encodeToJSON()
        nillableDictionary["filter"] = self.filter
        nillableDictionary["event_filters"] = self.eventFilters?.encodeToJSON()
        nillableDictionary["sorting"] = self.sorting?.encodeToJSON()
        nillableDictionary["offset"] = self.offset
        nillableDictionary["limit"] = self.limit?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
